
# @name createsite
POST http://localhost:8080/sites
content-type: application/json

{
    "start-url": "https://quarkus.io/guides",
    "main-url":  "https://quarkus.io",
    "inclusion-url": "https://quarkus.io/guides",
    "name": "QuarkusGuides",
    "display-name": "Quarkus Guides"
}

###

# @name createsitenewsletter
POST http://localhost:8080/sites
content-type: application/json

{
    "start-url": "https://quarkus.io/newsletter",
    "main-url":  "https://quarkus.io",
    "inclusion-url": "https://quarkus.io/newsletter/",
    "name": "QuarkusNewsletter",
    "display-name": "Quarkus Newsletters"
}

###

# @name createesitequte
POST http://localhost:8080/sites
content-type: application/json

{
    "start-url": "https://quarkus.io/guides/qute",
    "main-url":  "https://quarkus.io",
    "inclusion-url": "https://quarkus.io/guides/qute",
    "name": "QuarkusGuidesQute",
    "display-name": "Quarkus Guides Qute"
}

###

# @name createesitelogging
POST http://localhost:8080/sites
content-type: application/json

{
    "start-url": "https://quarkus.io/guides/logging",
    "main-url":  "https://quarkus.io",
    "inclusion-url": "https://quarkus.io/guides/logging",
    "name": "QuarkusGuidesLogging",
    "display-name": "Quarkus Guides Logging"
}

###

# @name getsite

GET http://localhost:8080/sites
Accept: application/json

###

# @name crawl

PUT http://localhost:8080/sites/QuarkusNewsletter/crawl
Accept: application/json

###

# @name search

GET http://localhost:8080/sites/QuarkusGuides/pages/search-by-text?pattern=cdi
Accept: application/json

###

# @name getversions

GET http://localhost:8080/clients/versions/linux
Accept: application/json

###

# @name getversionssw

GET http://localhost:8080/clients/versions/linux/0.0.1
Accept: application/octet-stream

###

# @name registerclient

POST http://localhost:8080/clients/registered
content-type: application/json

{
    "hostname": "somehost",
    "ip-address": "127.0.0.1",
    "user": "myself",
    "version": "0.0.1",
    "os": "mylinux"
}